<<<<<<< HEAD
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
=======
version: 2


jobs:
  build:
    docker: 
        -image: circleci/python:3.6.1
        
    working_directory: ~/repo
    steps:
      - checkout
      - run:
            name: install dep
            command: |
                python -m venv venv
                . venv/bin/activate
                make install
      - run:
            name: run lint
            command: | 
            . venv/bin/activate
            make lint

>>>>>>> 99983da69c4070387e9354a5320d6e31e4cc24ac
