version: 2


jobs:
  build:
    docker: 
        -image: circleci/python:3.6.1
        
    working_directory: ~/repo
    steps:
      - checkout
      - run:
            name: install dep
            command: |
                python -m venv venv
                . venv/bin/activate
                make install
      - run:
            name: run lint
            command: | 
            . venv/bin/activate
            make lint

